# Generated by Django 5.1.4 on 2024-12-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registrationtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtype',
            name='name',
            field=models.CharField(choices=[('Workshop 2', 'Workshop 2'), ('AIMER', 'AIMER'), ('Workshop 1', 'Workshop 1')], max_length=255),
        ),
    ]
