# Generated by Django 5.1.4 on 2025-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registrationtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='name',
            field=models.CharField(choices=[('AIMER', 'AIMER'), ('Workshop 1', 'Workshop 1'), ('Workshop 2', 'Workshop 2')], max_length=255),
        ),
    ]
