# Generated by Django 5.1.5 on 2025-01-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_participant_amount_paid_participant_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_aimer_member',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='registration_type',
        ),
        migrations.CreateModel(
            name='AimerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_member', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participant')),
                ('registration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationtype')),
            ],
        ),
    ]
