# Generated by Django 5.1.5 on 2025-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_participant_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppricing',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshoppricing',
            name='workshop_end_date',
            field=models.DateField(help_text='Date on which workshop ends', null=True),
        ),
        migrations.AddField(
            model_name='workshoppricing',
            name='workshop_start_date',
            field=models.DateField(help_text='Date on which workshop starts', null=True),
        ),
        migrations.AlterField(
            model_name='aimermember',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
