# Generated by Django 5.1.5 on 2025-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_workshoppricing_is_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimermember',
            name='is_active_member',
            field=models.BooleanField(default=True),
        ),
    ]
