# Generated by Django 5.1.5 on 2025-02-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_district_state_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppricing',
            name='brochure_link',
            field=models.URLField(blank=True, help_text='Link to the workshop brochure (This will be displayed in the registration form).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workshoppricing',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, help_text='WhatsApp group link for participants (Will be sent via email, not shown in form).', max_length=500, null=True),
        ),
    ]
