# Generated by Django 5.1.5 on 2025-03-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_workshoppricing_brochure_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Razorpay Payments',
            },
        ),
    ]
