version: "3.9"

services:
  web:
    image: ggpro/aimer_web:latest
    restart: always
    command: ["/bin/bash", "/code/web_init.sh"]
    
    volumes:
      - static_volume:/code/workshop_registration/staticfiles # Mount the static files where Django collects them
      - .:/code
      - media_volume:/code/media
      - ./web_init/web_init.sh:/code/web_init.sh
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf  # ✅ Mount file directly
      - ./.env:/code/.env
      - ./workshop_registration/data_to_import:/code/workshop_registration/data_to_import
      
      
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    env_file:
      - .env  # Explicitly load the .env file
    environment:
      - DJANGO_ENV=docker
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}  # Use the environment variable
      - DEBUG=1  # Turn off debug for production
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}  # Replace with your instance domain or IP
      - USE_TZ=True
      - TIME_ZONE=Asia/Kolkata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`aimerconsortium.labmasters.in`)"
      #- "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=le"
      - "traefik.http.services.web.loadbalancer.server.port=8000"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/var/www/static # Mount to where Nginx serves from
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`aimerconsortium.labmasters.in`) && PathPrefix(`/static`)"
      #- "traefik.http.routers.static.entrypoints=web"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=le"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    ports:
       - "8081:80" #Expose nginx on different port for testing, traefik will handle 80

  traefik:
    image: traefik:v2.10
    environment:
      - SSL_MAIL=${SSL_MAIL}
    env_file:
      - .env  # Explicitly load the .env file
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"    # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${SSL_MAIL}  # Replace with your email
      - --certificatesresolvers.le.acme.storage=/acme.json
      
      - --log.level=DEBUG
      - --api.dashboard=true
      - --api.insecure=false
      - --api=true


  db:
    image: postgres:15
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env  # Explicitly load the .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./healthcheck.sh:/healthcheck.sh  # Mount the script from the current directory
      - ./db_init:/docker-entrypoint-initdb.d/  # Mount the init script and init.sql

    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]  # Run the health check script
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  static_volume:
  media_volume:

# there are two staticfiles directory...
# need to add lets encrypt