entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      #email: "${SSL_MAIL}"
      storage: "/acme.json"
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
