# Generated by Django 5.1.4 on 2024-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_for', models.CharField(choices=[('Aimer', 'Aimer'), ('Workshop', 'Workshop')], max_length=400)),
            ],
        ),
    ]
