# Generated by Django 5.1.5 on 2025-03-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0014_razorpaypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_url', models.URLField(help_text='URL to fetch the certificate template (PNG, JPEG, or PDF)', max_length=500)),
                ('name_position_x', models.PositiveIntegerField(help_text="X-coordinate for placing participant's name on the template")),
                ('name_position_y', models.PositiveIntegerField(help_text="Y-coordinate for placing participant's name on the template")),
                ('font_size', models.PositiveIntegerField(default=40, help_text="Font size for the participant's name")),
                ('font_color', models.CharField(default='#000000', help_text="Font color for the participant's name in HEX (e.g., #000000)", max_length=7)),
                ('workshop', models.OneToOneField(help_text='Workshop this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='registration.registrationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_sent', models.BooleanField(default=False, help_text='Has the certificate email been sent?')),
                ('sent_on', models.DateTimeField(blank=True, help_text='Timestamp of when the certificate was sent', null=True)),
                ('participant', models.ForeignKey(help_text='Participant who attended the workshop', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_status', to='registration.participant')),
                ('workshop', models.ForeignKey(help_text='Workshop attended', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_status', to='registration.registrationtype')),
            ],
            options={
                'unique_together': {('workshop', 'participant')},
            },
        ),
    ]
